### ISSUE TITLE
non auth user

### ISSUE THREAD

**Issue by rasxod** [jaredfhealy/quickapi#3]
Как использовать модуль для неавторизованных пользователей

--

How to use the module for unauthorized users

**Comment by jaredfhealy** [comment]
Take a look at the snippet "ApiAuthorized". The notes at the top of that snippet indicate what you can do.

To modify the default behavior, use the "Duplicate" button on the snippet and name the new one, "MyApiAuthorized". It must be exactly that.
![image](https://user-images.githubusercontent.com/9794500/117859962-f144ab00-b24c-11eb-8028-da315a55fac9.png)

Then, modify the contents of the snippet script. You could simply put:

```php
// If the auth is false, a 403 response is returned
$auth = true;

return $auth;
```

Or it could be more complex and could have some other checks. Or maybe any API that starts with "/web_" can be public.

```php
if (str_starts_with($path[0], 'web_') {
  $auth = true;
}
```

As the readme mentions, the `$path` variable contains an array of the parts of the path. Example: `/api/hello/world` creates an array `["hello","world"]`.
